# Generated by Django 3.2.4 on 2021-06-27 12:30

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('film', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CinemaRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('column', models.IntegerField(default=10)),
                ('row', models.IntegerField(default=10)),
                ('seating', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.BooleanField(blank=True), size=None), blank=True, size=None)),
                ('films', models.ManyToManyField(to='film.Move')),
            ],
        ),
    ]
