# Generated by Django 3.2.4 on 2021-06-26 19:00

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_room', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cinemaroom',
            name='seating',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.BooleanField(default=False, null=True), size=10), null=True, size=10),
        ),
    ]
