# Generated by Django 3.2.4 on 2021-06-26 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_room', '0005_alter_cinemaroom_seating'),
    ]

    operations = [
        migrations.AddField(
            model_name='cinemaroom',
            name='column',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='cinemaroom',
            name='row',
            field=models.IntegerField(default=10),
        ),
    ]
