# Generated by Django 3.2.4 on 2021-06-26 19:31

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_room', '0006_auto_20210626_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cinemaroom',
            name='seating',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.BooleanField(blank=True), size=None), blank=True, size=None),
        ),
    ]
