# Generated by Django 3.2.4 on 2021-06-27 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MoveTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
            ],
            options={
                'verbose_name': 'Movie show time',
            },
        ),
        migrations.CreateModel(
            name='Move',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('move_time_length', models.FloatField()),
                ('movie_cover', models.ImageField(upload_to='film/uploads/')),
                ('move_time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='film.movetime')),
            ],
            options={
                'verbose_name': 'Move',
            },
        ),
    ]
