# Generated by Django 3.2.4 on 2021-06-26 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MoveTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
            ],
            options={
                'verbose_name': 'Movie show time',
            },
        ),
        migrations.CreateModel(
            name='Move',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('movie_cover', models.ImageField(upload_to='film/uploads/')),
                ('move_time', models.ManyToManyField(to='film.MoveTime')),
            ],
            options={
                'verbose_name': 'Moves',
            },
        ),
    ]
