# Generated by Django 3.2.4 on 2021-06-26 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0002_alter_move_movie_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='move',
            name='movie_cover',
            field=models.ImageField(upload_to='film/uploads/'),
        ),
    ]
